package vms.PanelForms;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import vms.IssuePass;
import vmsDao.StaffDao;

public class Staff extends javax.swing.JPanel {

    String vSName, vDesig, vDob, vDept, vType;
    public String vRegNoFromOwner;
    int vStaffIDDao;
    String adminVar;

    public String getAdminVar() {
        return adminVar;
    }

    public void setAdminVar(String adminVar) {
        this.adminVar = adminVar;
    }

    public Staff() {
        initComponents();

    }

    public void setRegNo(String regNo) {
        vRegNoFromOwner = regNo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sName = new javax.swing.JTextField();
        desig = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        issuePass = new javax.swing.JButton();
        dob = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 768));

        jLabel1.setText("Staff Name");

        jLabel2.setText("Designation");

        jLabel3.setText("Date of Birth");

        jLabel4.setText("Department");

        jLabel5.setText("Type (Teaching / Non Teaching");

        issuePass.setText("Issue Pass");
        issuePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sName)
                    .addComponent(desig)
                    .addComponent(dept)
                    .addComponent(type)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(285, 285, 285))
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(issuePass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(desig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)))
                .addGap(102, 102, 102)
                .addComponent(issuePass)
                .addContainerGap(312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void issuePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuePassActionPerformed

        vSName = sName.getText();
        vDesig = desig.getText();
        vDob = dob.getText();
        vDept = dept.getText();
        vType = type.getText();

        if (vSName.equals("") && vDesig.equals("") && vDob.equals("") && vDept.equals("") && vType.equals("")) {
            JOptionPane.showMessageDialog(this, "Fill Complete Form");
        } else {

            try {
                StaffDao staff = new StaffDao(vSName, vDesig, vDob, vDept, vType);
                staff.createStaff();
                vStaffIDDao = staff.getStaffID();
                System.out.println("Staff===staffID" + vStaffIDDao);
                System.out.println("Staff===Registration No" + vRegNoFromOwner);
                // Create a object of permanent pass class

                vmsDao.PPassDao ppass = new vmsDao.PPassDao(vRegNoFromOwner, vStaffIDDao);
                ppass.createPPass();

                System.out.println("Staff ===Pass No" + ppass.getPPass());
                if (ppass.isDflag() == true) {
                    JOptionPane.showMessageDialog(this, "Pass Number = " + ppass.getPPass());
                    this.setVisible(false);

                    SwingUtilities.windowForComponent(this).dispose();

                    vms.MainWindow.ip.clearIssuePass();
                }

            } catch (Exception x) {
                System.out.println("" + x);
            }
        }

    }//GEN-LAST:event_issuePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dept;
    private javax.swing.JTextField desig;
    private javax.swing.JTextField dob;
    private javax.swing.JButton issuePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
