/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vms.PanelForms;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import vms.OwnerMain;
import vmsDao.PPassDao;
import vmsDao.VisitorDao;

/**
 *
 * @author manoj
 */
public class Visitor extends javax.swing.JPanel {

    String vRegNoFromOwner;
    String vvName, vvDob, vvContact, vvAddress, vvPerson, vvPurpose;
    String vTPassNo;

    int vVisitorIDDao;

    public Visitor() {
        initComponents();
    }

    public void setRegNo(String vRegNoFromIssue) {
        vRegNoFromOwner = vRegNoFromIssue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vName = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        vPerson = new javax.swing.JTextField();
        purpose = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IssuePass = new javax.swing.JButton();
        dob = new javax.swing.JTextField();

        jLabel3.setText("Contact Number");

        jLabel4.setText("Address");

        jLabel5.setText("Visiting Person");

        jLabel6.setText("Purpose");

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jLabel1.setText("Visitor Name");

        jLabel2.setText("DOB");

        IssuePass.setText("Issue Pass");
        IssuePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuePassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(IssuePass))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(vPerson)
                            .addComponent(purpose)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vName, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(dob))))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(496, 496, 496)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(vName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purpose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(56, 56, 56)
                .addComponent(IssuePass)
                .addGap(63, 63, 63))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel1)
                    .addContainerGap(479, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IssuePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuePassActionPerformed

        vvName = vName.getText();
        vvDob = dob.getText();
        vvContact = contact.getText();
        vvAddress = address.getText();
        vvPerson = vPerson.getText();
        vvPurpose = purpose.getText();

        if (vvName.equals("") && vvDob.equals("") && vvContact.equals("") && vvAddress.equals("") && vvPerson.equals("") && vvPurpose.equals("")) {
            JOptionPane.showMessageDialog(this, "Fill Complete Form");
        } else {
            try {
                VisitorDao visitor = new VisitorDao(vvName, vvDob, vvContact, vvAddress, vvPerson, vvPurpose);
                visitor.createVisitor();
                vVisitorIDDao = visitor.getVisitorID();
                // Create a object of permanent pass class
                vmsDao.TPassDao tpass = new vmsDao.TPassDao(vRegNoFromOwner, vVisitorIDDao);

                System.out.println("RegNo and Visitor" + vRegNoFromOwner + "  " + vVisitorIDDao);

                tpass.createTempoPass();
                vTPassNo = tpass.getTPass();
                System.out.println("" + tpass.getTPass());

                JOptionPane.showMessageDialog(this, "Your Pass Number is " + vTPassNo);

                //CheckIN immediately
                vmsDao.CheckInTime cint = new vmsDao.CheckInTime();
                cint.setvPassNo(vTPassNo);
                cint.checkIN();
                if (cint.isDataok() == true) {
                    JOptionPane.showMessageDialog(this, "Check IN Done");
                    SwingUtilities.windowForComponent(this).dispose();
                    
                }
            } catch (Exception x) {
                System.out.println("" + x);
            }
        }


    }//GEN-LAST:event_IssuePassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IssuePass;
    private javax.swing.JTextArea address;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField purpose;
    private javax.swing.JTextField vName;
    private javax.swing.JTextField vPerson;
    // End of variables declaration//GEN-END:variables

}
