/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vmsReports;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manoj
 */
public class ReportByMonth extends javax.swing.JFrame {

    ArrayList<String> databasepids = new ArrayList<String>();
    ArrayList<String> databasecintimes = new ArrayList<String>();
    ArrayList<String> databasecouttimes = new ArrayList<String>();
    ArrayList<String> databaseregNo = new ArrayList<String>();
    ArrayList<String> databaseStaffName = new ArrayList<String>();
    ArrayList<String> databaseStaffDesig = new ArrayList<String>();
    ArrayList<Integer> databaseStaffID = new ArrayList<Integer>();
    
    DefaultTableModel model = new DefaultTableModel();
            

    /**
     * Creates new form ReportByDate
     */
    public ReportByMonth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        view = new javax.swing.JButton();
        monthtext = new javax.swing.JTextField();
        yeartext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportByDateTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Date");

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        monthtext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthtextFocusLost(evt);
            }
        });

        yeartext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                yeartextFocusLost(evt);
            }
        });

        jLabel2.setText("Enter in        MM / YYYY Format");

        ReportByDateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pass Number", "Vehicle Number", "Staff Name", "Designation", "Check IN", "Check Out"
            }
        ));
        jScrollPane1.setViewportView(ReportByDateTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(monthtext, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(yeartext, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(view)
                        .addGap(222, 222, 222))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(view)
                    .addComponent(monthtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeartext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed

        
        
        String dmonthString = monthtext.getText();
        String dyearString = yeartext.getText();
       
        try {
            //Getting data from masterdatetime
            vmsDao.ByMonthGet getdata = new vmsDao.ByMonthGet(dmonthString, dyearString);
            
            getdata.findByMonth();
            databasepids = getdata.getPids();
            //System.out.println("Super pass = = "+getdata.getPids());
            databasecintimes = getdata.getCintimes();
            databasecouttimes = getdata.getCouttimes();
            System.out.println("masterdatabse done");
        } catch (Exception x) {
            System.out.println("" + x);
        }
        
        Iterator testpassdata = databasepids.iterator();
        while(testpassdata.hasNext()){
            System.out.println("1..."+testpassdata.next());
        }
        
        Iterator itrpassdata = databasepids.iterator();
        while(itrpassdata.hasNext()){
            //Getting data from pass
            vmsDao.PassGet passget = new vmsDao.PassGet(itrpassdata.next().toString());
            passget.getPassDetails();
            databaseregNo.add(passget.getRegNo());
            databaseStaffID.add(passget.getStaffID());
            System.out.println("Wrong staddi=="+passget.getStaffID());
            databaseStaffID.add(passget.getStaffID());
            System.out.println("pass done::");
        }
        
        Iterator itrstaffid = databaseStaffID.iterator();
        while(itrstaffid.hasNext()){
            //getting data from staff
            vmsDao.StaffGet staffget = new vmsDao.StaffGet(Integer.parseInt(itrstaffid.next().toString()));
            System.out.println("staff id dta=="+staffget.getvStaffID());
            staffget.getStaffDetails();
            
            
            
            System.out.println("DATA STAFF  =="+staffget.getvSName());
            System.out.println("DATA STAFFDD === "+ staffget.getvDesig());
            databaseStaffName.add(staffget.getvSName());
            databaseStaffDesig.add(staffget.getvDesig());
            System.out.println("Staff done");
        }
        
        Iterator itr = databasepids.iterator();
        Iterator itrin = databasecintimes.iterator();
        Iterator itrout = databasecouttimes.iterator();
        Iterator itrreg = databaseregNo.iterator();
        Iterator itrstaffname = databaseStaffName.iterator();
        Iterator itrstaffdesig = databaseStaffDesig.iterator();
        Object[] trow = new Object[6];
        model.setRowCount(0);
        
        while (itr.hasNext()) {
            /*System.out.println(itr.next());
            System.out.println(itrin.next());
            System.out.println(itrout.next());*/
            //System.out.println("SNAME=="+itrstaffname.next());
            //System.out.println("SDESIG=="+itrstaffdesig.next());
           /*
             itrin.hasNext();
             itrout.hasNext();
             itrreg.hasNext(); 
             itrstaffname.hasNext();
             itrstaffdesig.hasNext();
            */
            model =(DefaultTableModel) ReportByDateTable.getModel();
            
            //Object[] row = new Object[6];
            /*Object[] row = {
              itr.next(), itrin.next(), itrout.next()
            };*/
            //model.addRow(row);
          // for (int i = 0; i < databasepids.size(); i++) {
           /* row[0] = databasepids;
            row[1] = databasepids;
            row[2] = databasepids;
            row[3] = databasepids;
            row[4] = databasecintimes;
            row[5] = databasecouttimes;
            model.addRow(row);*/
           //}
           
          trow[0] = itr.next();
           trow[1] = itrreg.next();
            trow[2] = itrstaffname.next();
            trow[3] = itrstaffdesig.next();
            trow[4] = itrin.next();
            trow[5] = itrout.next();
            model.addRow(trow);
        }
        

    }//GEN-LAST:event_viewActionPerformed

    private void setTableData() {
        DefaultTableModel model = (DefaultTableModel) ReportByDateTable.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < databasepids.size(); i++) {
            row[0] = databasepids.get(i);
            row[1] = databasepids.get(i);
            row[2] = databasepids.get(i);
            row[3] = databasepids.get(i);
            row[4] = databasepids.get(i);
            row[5] = databasepids.get(i);

        }

    }

    private void monthtextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthtextFocusLost

        if (monthtext.getText().length() == 2) {
        } else {
            monthtext.setText("");
            JOptionPane.showMessageDialog(this, "Enter a Valid Day in DD Format");
        }
    }//GEN-LAST:event_monthtextFocusLost

    private void yeartextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yeartextFocusLost

        if (yeartext.getText().length() == 4) {

        } else {
            yeartext.setText("");
            JOptionPane.showMessageDialog(this, "Enter a Valid Day in DD Format");
        }
    }//GEN-LAST:event_yeartextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportByMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportByMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportByMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportByMonth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportByMonth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ReportByDateTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monthtext;
    private javax.swing.JButton view;
    private javax.swing.JTextField yeartext;
    // End of variables declaration//GEN-END:variables
}
