/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vms;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vmsDao.VisitorDao;

/**
 *
 * @author manoj
 */
public class IssuePassVisitor extends javax.swing.JFrame {

    //Form variables
    private String vRegNo = "", vType = "", vModel = "", vColor = "";
    String adminStat;
    
    String vRegNoFromOwner;
    String vvName, vvDob, vvContact, vvAddress, vvPerson, vvPurpose;
    String vTPassNo;

    int vVisitorIDDao;


    public String getAdminStat() {
        return adminStat;
    }

    public void setAdminStat(String adminStat) {
        this.adminStat = adminStat;
    }

    public void clearIssuePass() {
        regNo.setText("");
        model.setText("");
        color.setText("");
        vType = "";
        jButton5.setEnabled(true);
    }

    public IssuePassVisitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        model = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        type4 = new javax.swing.JRadioButton();
        type2 = new javax.swing.JRadioButton();
        regNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        noteMsg = new javax.swing.JLabel();
        vName = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        vPerson = new javax.swing.JTextField();
        purpose = new javax.swing.JTextField();
        IssuePass = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        model.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        model.setBorder(null);
        model.setOpaque(false);
        getContentPane().add(model);
        model.setBounds(200, 460, 160, 20);

        color.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        color.setBorder(null);
        color.setOpaque(false);
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        getContentPane().add(color);
        color.setBounds(200, 510, 160, 20);

        buttonGroup3.add(type4);
        type4.setBorder(null);
        type4.setOpaque(false);
        type4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type4ActionPerformed(evt);
            }
        });
        getContentPane().add(type4);
        type4.setBounds(190, 390, 20, 13);

        buttonGroup3.add(type2);
        type2.setBorder(null);
        type2.setOpaque(false);
        type2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type2ActionPerformed(evt);
            }
        });
        getContentPane().add(type2);
        type2.setBounds(190, 420, 20, 13);

        regNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regNo.setBorder(null);
        regNo.setOpaque(false);
        regNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regNoFocusLost(evt);
            }
        });
        regNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNoActionPerformed(evt);
            }
        });
        getContentPane().add(regNo);
        regNo.setBounds(210, 310, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vehicle reg 2.png.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 366, 768);

        jButton5.setText("Add Owner");
        jButton5.setNextFocusableComponent(jMenuBar1);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(70, 590, 230, 40);
        getContentPane().add(noteMsg);
        noteMsg.setBounds(30, 550, 310, 20);
        getContentPane().add(vName);
        vName.setBounds(1000, 220, 250, 20);
        getContentPane().add(dob);
        dob.setBounds(1000, 280, 250, 20);
        getContentPane().add(contact);
        contact.setBounds(1000, 330, 250, 20);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(1000, 370, 250, 110);
        getContentPane().add(vPerson);
        vPerson.setBounds(1000, 510, 250, 20);
        getContentPane().add(purpose);
        purpose.setBounds(1000, 560, 250, 20);

        IssuePass.setText("Issue Pass");
        IssuePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssuePassActionPerformed(evt);
            }
        });
        getContentPane().add(IssuePass);
        IssuePass.setBounds(820, 650, 85, 23);

        jLabel7.setText("DOB");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 280, 60, 14);

        jLabel2.setText("Visitor Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 230, 100, 14);

        jLabel3.setText("Contact Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 340, 80, 10);

        jLabel4.setText("Address");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 400, 39, 10);

        jLabel5.setText("Visiting Person");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 510, 69, 14);

        jLabel6.setText("Purpose");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(570, 560, 39, 14);

        jMenu3.setText("Vehicle Pass");

        jMenuItem5.setText("Register Vehicle");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Main Window");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Main Window");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Reports");
        jMenuBar1.add(jMenu4);

        jMenu1.setText("Account");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Log Out");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        //Setting values from Form
        vRegNo = regNo.getText();

        vModel = model.getText();
        vColor = color.getText();

        //Showing Inserted Data
        System.out.println("vReg:" + vRegNo);
        System.out.println("vType:" + vType);
        System.out.println("vModel:" + vModel);
        System.out.println("vColor:" + vColor);

        Connection conn = null;
        Statement stmt = null;

        try {
            noteMsg.setText("");
            if (vRegNo.equals("") || vType.equals("") || vModel.equals("") || vColor.equals("")) {
                noteMsg.setText("Please Fill all Details");
            } else {
                vmsDao.VmsDatabase vd = new vmsDao.VmsDatabase();
                conn = vd.getConnection();
                stmt = conn.createStatement();
                String sql = "INSERT INTO vehicle "
                        + "VALUES ('" + vRegNo + "', '" + vType + "', '" + vModel + "', '" + vColor + "')";
                int x = stmt.executeUpdate(sql);

                if (x == 0) {

                    System.out.println("Fill Details");
                } else {
                    //New Windows for visitor or staff
                    jButton5.setEnabled(false);

                    regNo.setEditable(false);
                    model.setEditable(false);
                    color.setEditable(false);
                    vType = "";

                    JOptionPane.showMessageDialog(this, "Vehicle Added");
                    
                    regNo.setFocusable(false);
                    vName.setFocusable(true);
                }

            }//if close

        } catch (Exception ex) {
            System.out.println(ex);
        } finally {
            try {
                conn.close();
                stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(IssuePassVisitor.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void type4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type4ActionPerformed

        vType = "4 Wheeler";
    }//GEN-LAST:event_type4ActionPerformed

    private void type2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type2ActionPerformed

        vType = "2 Wheeler";
    }//GEN-LAST:event_type2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed

        /*this.dispose();
        new LoginForm().setVisible(true);
         */
        JOptionPane.showMessageDialog(this, "Please Logout From Main Window");
        this.dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void regNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regNoFocusGained

        //jButton5.setEnabled(true);
    }//GEN-LAST:event_regNoFocusGained

    private void regNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regNoFocusLost

        //Check for existing registration number
        vmsDao.VehicleGet vrg = new vmsDao.VehicleGet();
        vrg.setvRegNo(regNo.getText());
        vrg.getVehicleDetails();
        if (vrg.isDataok() == true) {
            jButton5.setEnabled(false);

            regNo.setEditable(false);
            model.setEditable(false);
            color.setEditable(false);
            vType = "";

            JOptionPane.showMessageDialog(this, "Vehicle Details Found");
            
            jButton5.setEnabled(false);
            color.setFocusable(true);
        }
    }//GEN-LAST:event_regNoFocusLost

    private void regNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNoActionPerformed

    private void IssuePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssuePassActionPerformed

        vvName = vName.getText();
        vvDob = dob.getText();
        vvContact = contact.getText();
        vvAddress = address.getText();
        vvPerson = vPerson.getText();
        vvPurpose = purpose.getText();

        if (vvName.equals("") && vvDob.equals("") && vvContact.equals("") && vvAddress.equals("") && vvPerson.equals("") && vvPurpose.equals("")) {
            JOptionPane.showMessageDialog(this, "Fill Complete Form");
        } else {
            try {
                VisitorDao visitor = new VisitorDao(vvName, vvDob, vvContact, vvAddress, vvPerson, vvPurpose);
                visitor.createVisitor();
                vVisitorIDDao = visitor.getVisitorID();
                // Create a object of permanent pass class
                vmsDao.TPassDao tpass = new vmsDao.TPassDao(vRegNo, vVisitorIDDao);

                System.out.println("RegNo and Visitor" + vRegNo + "  " + vVisitorIDDao);

                tpass.createTempoPass();
                vTPassNo = tpass.getTPass();
                System.out.println("" + tpass.getTPass());

                

                //CheckIN immediately
                vmsDao.CheckInTime cint = new vmsDao.CheckInTime();
                cint.setvPassNo(vTPassNo);
                cint.checkIN();
                if (cint.isDataok() == true) {
                    JOptionPane.showMessageDialog(this, "Your Pass Number is " + vTPassNo);
                    

                }
                
            } catch (Exception x) {
                System.out.println("" + x);
            }
            
        }

    }//GEN-LAST:event_IssuePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuePassVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuePassVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuePassVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuePassVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuePassVisitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IssuePass;
    private javax.swing.JTextArea address;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField color;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dob;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField model;
    private javax.swing.JLabel noteMsg;
    private javax.swing.JTextField purpose;
    private javax.swing.JTextField regNo;
    private javax.swing.JRadioButton type2;
    private javax.swing.JRadioButton type4;
    private javax.swing.JTextField vName;
    private javax.swing.JTextField vPerson;
    // End of variables declaration//GEN-END:variables
}
