/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vms;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author manoj
 */
public class IssuePass extends javax.swing.JFrame {

    //Form variables
    private String vRegNo = "", vType = "", vModel = "", vColor = "";
    String adminStat;

    public String getAdminStat() {
        return adminStat;
    }

    public void setAdminStat(String adminStat) {
        this.adminStat = adminStat;
    }

    public void clearIssuePass() {
        regNo.setText("");
        model.setText("");
        color.setText("");
        vType = "";
        jButton5.setEnabled(true);
    }

    public IssuePass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup3 = new javax.swing.ButtonGroup();
        model = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        type4 = new javax.swing.JRadioButton();
        type2 = new javax.swing.JRadioButton();
        regNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        noteMsg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        model.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        model.setBorder(null);
        model.setOpaque(false);
        getContentPane().add(model);
        model.setBounds(200, 460, 160, 20);

        color.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        color.setBorder(null);
        color.setOpaque(false);
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        getContentPane().add(color);
        color.setBounds(200, 510, 160, 20);

        buttonGroup3.add(type4);
        type4.setBorder(null);
        type4.setOpaque(false);
        type4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type4ActionPerformed(evt);
            }
        });
        getContentPane().add(type4);
        type4.setBounds(190, 390, 20, 13);

        buttonGroup3.add(type2);
        type2.setBorder(null);
        type2.setOpaque(false);
        type2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type2ActionPerformed(evt);
            }
        });
        getContentPane().add(type2);
        type2.setBounds(190, 420, 20, 13);

        regNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regNo.setBorder(null);
        regNo.setOpaque(false);
        regNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                regNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                regNoFocusLost(evt);
            }
        });
        regNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNoActionPerformed(evt);
            }
        });
        getContentPane().add(regNo);
        regNo.setBounds(210, 310, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vehicle reg 2.png.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 366, 768);

        jButton5.setText("Add Owner");
        jButton5.setNextFocusableComponent(jMenuBar1);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(70, 590, 230, 40);

        jLabel7.setText("Registration Number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 250, 110, 14);

        jLabel8.setText("Type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 289, 40, 14);

        jLabel9.setText("Model");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 326, 60, 24);

        jLabel10.setText("Color");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 373, 40, 14);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(703, 500));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(369, 0, 1000, 768);
        getContentPane().add(noteMsg);
        noteMsg.setBounds(20, 510, 320, 30);

        jMenu3.setText("Vehicle Pass");

        jMenuItem5.setText("Register Vehicle");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Main Window");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("Main Window");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Reports");
        jMenuBar1.add(jMenu4);

        jMenu1.setText("Account");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Log Out");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        //Setting values from Form
        vRegNo = regNo.getText();

        vModel = model.getText();
        vColor = color.getText();

        //Showing Inserted Data
        System.out.println("vReg:" + vRegNo);
        System.out.println("vType:" + vType);
        System.out.println("vModel:" + vModel);
        System.out.println("vColor:" + vColor);

        Connection conn = null;
        Statement stmt = null;

        try {
            noteMsg.setText("");
            if (vRegNo.equals("") || vType.equals("") || vModel.equals("") || vColor.equals("")) {
                noteMsg.setText("Please Fill all Details");
            } else {
                vmsDao.VmsDatabase vd = new vmsDao.VmsDatabase();
                conn = vd.getConnection();
                stmt = conn.createStatement();
                String sql = "INSERT INTO vehicle "
                        + "VALUES ('" + vRegNo + "', '" + vType + "', '" + vModel + "', '" + vColor + "')";
                int x = stmt.executeUpdate(sql);

                if (x == 0) {

                    System.out.println("Fill Details");
                } else {
                    //New Windows for visitor or staff
                    jButton5.setEnabled(false);

                    regNo.setEditable(false);
                    model.setEditable(false);
                    color.setEditable(false);
                    vType = "";

                    OwnerMain om = new OwnerMain();
                    JOptionPane.showMessageDialog(this, "Vehicle Added");
                    om.setRegNo(vRegNo);
                    om.sendRegistrationNo();
                    System.out.println("Issue Pass ==== regNo=" + vRegNo);

                    //MainWindow.omain.setRegNo(vRegNo);
                    jDesktopPane1.add(om);
                    //om.setVisitor(false);
                    //om.setVisible(true);
                    om.setVisible(true);
                    if (adminStat.equalsIgnoreCase("no")) {
                        om.setStaff(false);
                    }

                    regNo.setFocusable(false);
                    color.setFocusable(true);
                }

            }//if close

        } catch (Exception ex) {
            System.out.println(ex);
        } finally {
            try {
                conn.close();
                stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(IssuePass.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void type4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type4ActionPerformed

        vType = "4 Wheeler";
    }//GEN-LAST:event_type4ActionPerformed

    private void type2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type2ActionPerformed

        vType = "2 Wheeler";
    }//GEN-LAST:event_type2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed

        /*this.dispose();
        new LoginForm().setVisible(true);
         */
        JOptionPane.showMessageDialog(this, "Please Logout From Main Window");
        this.dispose();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void regNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regNoFocusGained

        //jButton5.setEnabled(true);
    }//GEN-LAST:event_regNoFocusGained

    private void regNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regNoFocusLost

        //Check for existing registration number
        vmsDao.VehicleGet vrg = new vmsDao.VehicleGet();
        vrg.setvRegNo(regNo.getText());
        vrg.getVehicleDetails();
        if (vrg.isDataok() == true) {
            jButton5.setEnabled(false);

            regNo.setEditable(false);
            model.setEditable(false);
            color.setEditable(false);
            vType = "";

            OwnerMain om = new OwnerMain();
            JOptionPane.showMessageDialog(this, "Vehicle Details Found");
            om.setRegNo(vRegNo);
            om.sendRegistrationNo();
            System.out.println("Issue Pass ==== regNo=" + vRegNo);

            //MainWindow.omain.setRegNo(vRegNo);
            jDesktopPane1.add(om);
            //om.setVisitor(false);
            //om.setVisible(true);
            om.setVisible(true);
            if (adminStat.equalsIgnoreCase("no")) {
                om.setStaff(false);
            }
            jButton5.setEnabled(false);
            color.setFocusable(true);
        }
    }//GEN-LAST:event_regNoFocusLost

    private void regNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssuePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssuePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssuePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssuePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssuePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField color;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JTextField model;
    private javax.swing.JLabel noteMsg;
    private javax.swing.JTextField regNo;
    private javax.swing.JRadioButton type2;
    private javax.swing.JRadioButton type4;
    // End of variables declaration//GEN-END:variables
}
